### ISSUE TITLE
Have updates to working bits and fixes to adc - if interested, I can issue a pull request here or...

### ISSUE THREAD

**Issue by anotherstevest2** [SillyFreak/embassy-experiments#1]
Greetings,

I found embassy-experiments to be a great place for me to advance my (embassy) rust on STM32F3Discovery experience.  I cloned your repo, updated the previously working code and then debugged the adc demo (I'll do the serial port next).  In the process, I've identified a couple of Embassy bugs that I intend to bring to their attention (assuming they haven't already been identified...).  So... I desire to make my code public and I can either issue a pull request against your repo (so you get full originator presentation) or just make my repo public.

Do you have a preference?

**Comment by ensko** [comment]
Hi, thanks you found my repo useful! I think I would prefer you just making your repo public, then it's clear you authored the fixes and can add new stuff independently. Also, as it's just an experiments repo I'm not doing a lot of maintenance (obviously), so overall that approach makes more sense to me. I'll be interested to see your fixes, in any case!

**Comment by ensko** [comment]
I have added a license (MIT) to make it unambiguous that that this is ok to do with my code.

**Comment by anotherstevest2** [comment]
Thanks for responding and for generating the original code.  My enhancements (if I should be so bold as to call them that...) can be found here: https://github.com/anotherstevest2/embassy-experiments

**Comment by anotherstevest2** [comment]
No issue remaining...
